path_classifiers:
  externals:
    exclude: "contrib/"
  examples:
    exclude: "examples/"
  rest:
    exclude: "rest/"
extraction:
  cpp:
    after_prepare:
    - "mkdir custom_cmake"
    - "wget --quiet -O - \"http://www.cmake.org/files/v3.20/cmake-3.20.3-linux-x86_64.tar.gz\"\
      \ | tar --strip-components=1 -xz -C custom_cmake"
    - "export PATH=$(pwd)/custom_cmake/bin:${PATH}"
    - "wget --quiet -O - \"https://www.star.bnl.gov/~dmitry/tmp/soci-4-include.tar.gz\"\
      \ | tar -xz --strip-components=1 -C contrib"
    - "mkdir extra_libs"
    - "wget --quiet -O - \"https://www.star.bnl.gov/~dmitry/tmp/soci-4-lib.tar.gz\"\
      \ | tar -xz --strip-components=1 -C extra_libs"
    configure:
      command: "cmake -S lib -B lib/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=TRUE\
        \ -DCMAKE_PREFIX_PATH=$PWD/extra_libs"
    index:
      build_command: "cmake --build lib/build --clean-first -j 4"
